version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gocars
    ports:
      - "8080:8081"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    volumes:
      - ./pkg/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@db:5432/gocars?sslmode=disable", "up" ]
    depends_on:
      - db
volumes:
  pgdata: